apiVersion: v1
kind: Service
metadata:
  name: repo-analyzer-svc
  namespace: default
spec:
  selector:
    app: bram-vortex-repo-analyzer
  ports:
    - protocol: TCP
      port: 80       # Port μέσα στο Cluster
      targetPort: 8080 # Port του Spring Boot
  type: ClusterIP