apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-repo-analyzer
  namespace: default
  labels:
    app: bram-vortex-repo-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-repo-analyzer
  template:
    metadata:
      labels:
        app: bram-vortex-repo-analyzer
    spec:
      serviceAccountName: repo-analyzer-sa
      containers:
        - name: repo-analyzer
          image: christosbramis/bram-vortex-repo-analyzer:537a2e400b4ddd16794d61a03f9864a558068dcc
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "1000m"