apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-repo-analyzer
  namespace: default
  labels:
    app: bram-vortex-repo-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-repo-analyzer
  template:
    metadata:
      labels:
        app: bram-vortex-repo-analyzer
    spec:
      # Χρήση του εξουσιοδοτημένου Service Account
      serviceAccountName: vault-serviceaccount
      containers:
        - name: repo-analyzer
          image: christosbramis/bram-vortex-repo-analyzer:89349840081505851a6a17d0a023a732f84dfa0a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # Endpoint Βάσης Δεδομένων
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/vortexdb"

            # Credentials Βάσης από το CSI Bundle
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: analyzer-secrets-bundle
                  key: db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analyzer-secrets-bundle
                  key: db-pass

            # Gemini API Key από το CSI Bundle
            - name: SPRING_AI_GOOGLE_GENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: analyzer-secrets-bundle
                  key: google-api-key

            # JPA Settings
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "analyzer-vault-provider"