apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-repo-analyzer
  namespace: default
  labels:
    app: bram-vortex-repo-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-repo-analyzer
  template:
    metadata:
      labels:
        app: bram-vortex-repo-analyzer
    spec:
      # Συνδέουμε το Pod με τη νέα ταυτότητα
      serviceAccountName: repo-analyzer-sa

      containers:
        - name: repo-analyzer
          image: christosbramis/bram-vortex-repo-analyzer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

          # --- Environment Variables ---
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: SPRING_APPLICATION_NAME
              value: "bram-vortex-repo-analyzer"

            - name: SPRING_CLOUD_VAULT_URI
              value: "http://vault.default.svc.cluster.local:8200"
            - name: SPRING_CLOUD_VAULT_AUTHENTICATION
              value: "KUBERNETES"

            - name: SPRING_CLOUD_VAULT_KUBERNETES_ROLE
              value: "repo-analyzer-role"

          # Resources (Προσαρμοσμένα για Java + AI processing)
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "768Mi" # Λίγο παραπάνω μνήμη αν φορτώνει μεγάλα repos
              cpu: "1000m"

          # Health Checks
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10