apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-repo-analyzer
  namespace: default
  labels:
    app: bram-vortex-repo-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-repo-analyzer
  template:
    metadata:
      labels:
        app: bram-vortex-repo-analyzer
    spec:
      serviceAccountName: repo-analyzer-sa
      containers:
        - name: repo-analyzer
          image: christosbramis/bram-vortex-repo-analyzer:683a1e16b2c462eb0b89d412005ed4c708568d86
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
