apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-frontend
  namespace: default
  labels:
    app: bram-vortex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-frontend
  template:
    metadata:
      labels:
        app: bram-vortex-frontend
    spec:
      containers:
        - name: frontend
          image: christosbramis/bram-vortex-frontend:ced8b5a0d786ea283ddb8ef1a73c4ea3e81abdce
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Το Nginx ακούει στην 80