apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-frontend
  namespace: default
  labels:
    app: bram-vortex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-frontend
  template:
    metadata:
      labels:
        app: bram-vortex-frontend
    spec:
      containers:
        - name: frontend
          image: christosbramis/bram-vortex-frontend:75ea306bb5c08c53067bde9599d938be8424695b
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Το Nginx ακούει στην 80