apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bram-vortex-postgres
  namespace: default
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-postgres
  template:
    metadata:
      labels:
        app: bram-vortex-postgres
    spec:
      # ΠΡΟΣΟΧΗ: Βάζουμε το service account που έχει δικαίωμα να μιλάει στο Vault!
      serviceAccountName: vault-serviceaccount
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-vault-secret # Διαβάζει από το μυστικό που φτιάχνει το Vault CSI
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-vault-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-vault-secret
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            # Mount το CSI Volume
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        # Ορισμός του CSI Volume για τη Βάση
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-postgres-provider"